[versions]
agp = "8.13.2"
kotlin = "2.2.21"
coreKtx = "1.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
lifecycleRuntimeKtx = "2.6.1"
activityCompose = "1.8.0"
composeBom = "2024.09.00"
lifecycleCompose = "2.8.0"

permission = "0.37.3"
navgation = "2.9.5"
coil3 = "3.3.0"
exoplayer = "1.9.0"
splashscreen = "1.0.0"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }

#Permission
google-accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions" , version.ref = "permission"}

#Navigation
navigation-compose =  { module = "androidx.navigation:navigation-compose" , version.ref = "navgation"}

#Coil
coil3-compose = { module = "io.coil-kt.coil3:coil-compose" , version.ref = "coil3"}
coil3-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil3" }
coil3 = { module = "io.coil-kt.coil3:coil" , version.ref = "coil3"}

#ExoPlayer
exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash" , version.ref = "exoplayer"}
exoplayer = { module = "androidx.media3:media3-exoplayer" , version.ref = "exoplayer"}

#SplashScreen
splash-core = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[bundles]
coil3-bundle = [
    "coil3","coil3-compose","coil3-network"
]